# Generated by Django 3.0.5 on 2020-05-19 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('races', models.CharField(default='bg', max_length=100, null=True)),
                ('club', models.CharField(choices=[('BRC', 'BRC'), ('TRIBE', 'TRIBE'), ('ADIDAS', 'ADIDAS')], default='BRC', max_length=50, null=True)),
                ('birth_date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Place of race organization')),
                ('length', models.IntegerField(choices=[(5, 5), (10, 10), (21, 21), (42, 42), (50, 50), (100, 100)], default=21, verbose_name='Length of race in km')),
                ('name', models.CharField(max_length=100, verbose_name='Official race name')),
                ('type', models.CharField(choices=[('road', 'road'), ('trail', 'trail')], default='road', max_length=100, verbose_name='Road or Trail')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of race for each year')),
                ('finished', models.BooleanField(default=False, verbose_name='True if race is marked as finished')),
            ],
            options={
                'ordering': ['date', 'length'],
            },
        ),
        migrations.CreateModel(
            name='UserRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.Profile')),
                ('race_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('detail', models.CharField(max_length=200)),
                ('date_earned', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Profile')),
                ('race_earned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
            ],
        ),
    ]
