# Generated by Django 3.0.5 on 2020-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='neko_novo_sranje',
            field=models.CharField(default='babab', max_length=10),
            preserve_default=False,
        ),
    ]
