# Generated by Django 3.0.5 on 2020-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_auto_20200519_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofej',
            name='race_earned',
        ),
        migrations.AddField(
            model_name='trofej',
            name='koje_trke',
            field=models.ManyToManyField(to='race.Race'),
        ),
    ]
