# Generated by Django 3.0.5 on 2020-05-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_auto_20200519_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trofej',
            name='koje_trke',
        ),
        migrations.AddField(
            model_name='trofej',
            name='race_earned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Race'),
        ),
    ]
