# Generated by Django 3.0.5 on 2020-05-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_auto_20200519_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trofej',
            new_name='Trophy',
        ),
    ]
