# Generated by Django 3.0.5 on 2020-05-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0006_auto_20200520_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='date_earned',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='race_earned',
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Profile')),
                ('race_earned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Trophy')),
            ],
        ),
    ]
