# Generated by Django 3.0.6 on 2020-05-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0007_auto_20200521_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRaces',
        ),
    ]
