# Generated by Django 3.0.6 on 2020-05-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_delete_userraces'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Race time in seconds', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('profile_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.Profile')),
                ('race_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='race.Race')),
            ],
        ),
    ]
