# Generated by Django 3.0.6 on 2020-05-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0009_userraces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userraces',
            old_name='Race time in seconds',
            new_name='time',
        ),
    ]
