# Generated by Django 3.0.6 on 2020-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0011_auto_20200526_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='New birth of runner',
        ),
        migrations.AddField(
            model_name='profile',
            name='started_running',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='User started to run'),
        ),
    ]
