# Generated by Django 3.0.6 on 2020-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0013_auto_20200531_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='started_running',
            field=models.DateField(null=True, verbose_name='User started to run'),
        ),
        migrations.AlterField(
            model_name='race',
            name='length',
            field=models.IntegerField(choices=[(5, 'fun'), (10, '10k'), (21, 'halfmarathon'), (42, 'marathon'), (50, 'ultra'), (100, 'long ultra')], default=21, verbose_name='Length of race in km'),
        ),
    ]
