# Generated by Django 3.0.6 on 2020-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0014_auto_20200703_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.CharField(max_length=100)),
                ('watch', models.CharField(max_length=100)),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50)),
                ('shorts_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='f', max_length=10),
            preserve_default=False,
        ),
    ]
