# Generated by Django 3.0.6 on 2020-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200721_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='injuries',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='target_race',
            field=models.CharField(max_length=50),
        ),
    ]
