# Generated by Django 3.0.6 on 2020-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200721_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='goals',
            field=models.CharField(max_length=50),
        ),
    ]
