# Generated by Django 3.0.6 on 2020-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200721_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('manager', 'manager'), ('organizer', 'organizer')], max_length=50),
        ),
    ]
