# Generated by Django 3.0.6 on 2020-07-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200721_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
