# Generated by Django 3.0.6 on 2020-07-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0016_usergear'),
        ('manager', '0006_delete_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Staff')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.Profile')),
            ],
        ),
    ]
