# Generated by Django 3.0.6 on 2020-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20200725_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanarina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('time', 'time'), ('distance', 'distance'), ('mixed', 'mixed')], max_length=50)),
                ('length', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='jun', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='plan',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
