# Generated by Django 3.0.6 on 2020-07-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_monthplan_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.TrainingPlan'),
        ),
    ]
