# Generated by Django 3.0.6 on 2020-07-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20200731_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TrainingPlan'),
        ),
    ]
