# Generated by Django 3.0.6 on 2020-08-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20200731_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingPlan',
            new_name='OneTrainingPlan',
        ),
    ]
