# Generated by Django 3.0.6 on 2020-08-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20200801_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthTrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MonthPlan')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Training')),
            ],
        ),
    ]
