# Generated by Django 3.0.6 on 2020-08-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_monthtrainingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthtrainingplan',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='manager.Group'),
            preserve_default=False,
        ),
    ]
